# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ajkqrYMyT9amUSbWFdIHpoitIJUpcqLx
"""

#1
import bokeh.io
import bokeh.plotting
bokeh.io.output_notebook()

pip install bokeh

#2
#Glyphs are the building blocks of Bokeh visualizations. A glyph is a vectorized graphical shape or marker that is used to represent your data. Here are a few different categories of glyphs. 00:15 They can be a marker—shapes like circles, diamonds, squares, and triangles

# import the libraries
from bokeh.plotting import figure, show, output_file

# prepare some data
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# create a plot using figure
my_plot = figure(title="simple line chart", x_axis_label="X-Axis",
                 y_axis_label="Y-Axis")

# adding line graph
my_plot.line(a, b, line_width=3)

# display output in file
output_file("line.html")

# show the result
show(my_plot)

#3
#With Bokeh’s themes, you can quickly change the appearance of your plot. Themes are a set of pre-defined design parameters such as colors, fonts, or line styles.

#Bokeh comes with five built-in themes: caliber, dark_minimal, light_minimal, night_sky, and contrast. Additionally, you can define your own custom themes.

#To use one of the built-in themes, assign the name of the theme you want to use to the theme property of your document:

#4
'''Bokeh server makes it easy to create interactive web applications that connect front-end UI events to running Python code. Bokeh creates high-level Python models, such as plots, ranges, axes, and glyphs, and then converts these objects to JSON to pass them to its client library, BokehJS'''

#5
#Bokeh is an interactive visualization library that helps us to create a visual representation of data set and interact with it. You can create various types of visualizations such as bar charts, horizontal plots,time-series, etc. There are various methods to include Bokeh apps and widgets into web apps and pages.  '''

